### ISSUE TITLE
External classes aren't resolved correctly and therefore show up as errors

### ISSUE THREAD

**Issue by florianb** [AtomLinter/linter-javac#1]
This is because at the moment there's no specific class-path specified and `javac` falls back searching the working directory and the user-specified classpath.

Therefore a search-strategy must be found to correctly resolve classpaths for different project types (like maven, gradle, eclipse and so on). A unresolved question is if the linter should enable the compiler to detect if the setting-files are correct or not.

**Comment by tgaurnier** [comment]
Does Atom provide a way for packages to get the root project directory? If so wouldn't it be easier to just recursively scan the project directory for .java files and add them all to the class path? Also maybe you can add support for some type of a .classpath file in the root of the project directory? I know that AtomLinter lints files from a temporary directory, but if you are passing all the 'class path' values as absolute paths it shouldn't make a difference where the linting is taking place. If there ends up being an issue with the file being linted also being in the classpath, just strip the existing file from the classpath during the linting process.

**Comment by nelsonmenezes** [comment]
Building on the "per project config" idea from @tgaurnier, a "project type" setting could allow for the classpath discovery mechanism. For Maven, for instance, it could use this: https://maven.apache.org/plugins/maven-dependency-plugin/build-classpath-mojo.html

**Comment by lunij** [comment]
This is an one year old issue. Is there someone still interested to implement this? Otherwise this package is totally useless without this implementation.

**Comment by viniciuspires** [comment]
I'm also affected by this. I still haven't messed around with Atom Linters API, but does it allow an easy way of per-project configuration? If it does would it be simple as classpath configuration to pass via `-cp` argument, or am I over-simplifying it?

**Comment by lunij** [comment]
That's the question. I don't have much experience with the Atom API yet, otherwise I'd try out exactly @viniciuspires's approach.

**Comment by skylineproject** [comment]
I'm somewhat familiar with the Atom API, I'll give the -cp method a go this afternoon. :)

**Comment by tgaurnier** [comment]
@lunij, the package isn't "totally" useless, there is a workaround that we can use in the meantime. Open a terminal in the root directory of your project, and launch Atom as such:
CLASSPATH="classpath_1:classpath_2:etc." atom .

This way Atom and all of it's sub-processes will share the class paths, and all should work as expected. Don't get me wrong, we shouldn't have to resort to this, but it's at least a usable workaround. What I do is just create an 'atom' script at the root of my project with the command in it, then I just run `atom` from a terminal in my project root directory.

**Comment by steelbrain** [comment]
Please note that this bug will be fixed as soon as this linter upgrades to the new Plus API.

**Comment by nelsonmenezes** [comment]
@tgaurnier that's quite neat. Then, for Maven projects you can do this:
```
CLASSPATH=`mvn dependency:build-classpath | grep -A 1 "Dependencies classpath" | tail -n1` atom .

**Comment by viniciuspires** [comment]
@nelsonmenezes Genious solution.

**Comment by daw42** [comment]
This issue should be resolved by PR #23 .  However, we should also make the classpath user-configurable.  I suggest we close this in favor of #25

**Comment by k2b6s9j** [comment]
Closing at the recommendation of @daw42.

**Comment by lsunsi** [comment]
Is this solved yet? I'm having the same problem and can't see documentation about how to fix this.
