### ISSUE TITLE
sb/execs cwd-argument has been dropped

### ISSUE THREAD

**Issue by florianb** [AtomLinter/linter-javac#100]
It seems like has dropped the [`cwd`-argument](https://github.com/AtomLinter/linter-javac/blob/master/lib/init.coffee#L197) according to the project's readme: https://github.com/steelbrain/exec/blob/master/README.md

Therefore the cwd-argument may be dropped safely?

**Comment by Arcanemagus** [comment]
The `cwd` argument was never part of `exec`, it _is_ however forwarded on to Node's [`child_process.spawn()`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options). If setting the `cwd` is useful, you should definitely still be passing it in 😉.

**Comment by florianb** [comment]
Ah, thanks for clarification. I guess the rewrite should include proper documentation, too.

Am 03.06.2016 7:40 nachm. schrieb Landon Abney <notifications@github.com>:

The cwd argument was never part of exec, it is however forwarded on to Node's child_process.spawn()<https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options>. If setting the cwd is useful, you should definitely still be passing it in ?.

-
