### ISSUE TITLE
Ignores maven dependencies while linting

### ISSUE THREAD

**Issue by snood1205** [AtomLinter/linter-javac#103]
I'm using this for a maven project and in my `pom.xml` I have

``` xml
<dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
</dependency>
```

however, in my test files I have the lines

``` java
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
```

Despite `mvn test` running completely fine and `junit` being explicitely specified in my `pom.xml` the linter still marks `org.junit` as a package that does not exist.

**Comment by florianb** [comment]
Hi @snood1205, thanks for getting in touch. Unfortunately we don't recognise any 3rd-party configurations like Maven, yet.

If JUnit isn't available on your default classpath you might consider adding a .classpath-file to your project.

Does this solve your issue?

**Comment by florianb** [comment]
I close this issue due to missing response.

**Comment by zygimantus** [comment]
So what is a generic solution for this problem? Because I am also getting errors with import org.apache.log4j.Logger which is defined in pom.xml file while using linter.

**Comment by florianb** [comment]
Hi @zygimantus - you currently have to make your classes available via `.classpath` file or any additional classpath settings (in the settings of the linter or as environment-variable).

**Comment by zygimantus** [comment]
Thanks, I tried this config, but the warning is still on, maybe you can see the problem?:

<?xml version="1.0" encoding="UTF-8"?>
<classpath>
  <classpathentry kind="src" path="src/test/java" output="target/test-classes" including="**/*.java"/>
  <classpathentry kind="src" path="src/main/java" including="**/*.java"/>
  <classpathentry kind="src" path="src/main/resources" excluding="**/*.java"/>
  <classpathentry kind="output" path="target/classes"/>
  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
  <classpathentry kind="var" path="M2_REPO/log4j/log4j/1.2.17/log4j-1.2.17.jar" sourcepath="M2_REPO/log4j/log4j/1.2.17/log4j-1.2.17-sources.jar"/>
</classpath>

This file is on the base of project.

**Comment by zygimantus** [comment]
Nevermind, I solved this when I set the M2_REPO variable in Additional Java Options input like this **M2_REPO=~/.m2/repository**
