### ISSUE TITLE
linter-javac doesn't execute javac

### ISSUE THREAD

**Issue by stanleynguyen** [AtomLinter/linter-javac#109]
Normally, linter-javac auto-compile my java file whenever I save new changes. However, it doesn't compile anymore thus only able to check my syntax.

**Comment by florianb** [comment]
Hey @stanleynguyen -- thanks for reporting and sorry to hear it doesn't work. You might want to try enabling the `Verbose Logging` in the settings of the linter-javac-package.

It should then output log-entries to your developer console `Window: Toggle Dev Tools`. It would help potential debugging if you could post the log output.

Please do not forget to disable `Verbose Logging` after debugging, to avoid performance issues.

**Comment by stanleynguyen** [comment]
found the problem! Because there were too many run time errors from files that reside inside a subdir  so linter-javac couldn't report.

**Comment by florianb** [comment]
Thanks for getting back @stanleynguyen, could you tell me at which number of errors this broke down? I didn't expect there being a limit within reach.. Thanks in advance! 💝

**Comment by stanleynguyen** [comment]
I'm not sure how many but it's alot because my subdir contains my android app, which will give me a lot of not found symbols. So there's no problem with my current open program, just that it doesnt auto compile a .class file due to the many problems in the subdir
I would suggest to have a .linterrc file so we can ignore subdir or put some configurations inside
