### ISSUE TITLE
Support for -d option, destination of .class files

### ISSUE THREAD

**Issue by torkelrogstad** [AtomLinter/linter-javac#110]
Although I love this package dearly, I'm regularly frustrated by having `.class` files _everywhere_. Would it be possible to supporting an (optional) option of setting the `-d` option of `javac`? This specifies where the `.class` files will be put. 

I'd be happy to have a go at implementing this myself, if someone would give me some pointers to where to start. Would  I be correct in assuming most of the magic happens in `init.coffee`? I'm sorry if this is asking stupid questions, but I have no experience in developing functionality in a project like Atom.

**Comment by keskiju** [comment]
Package already supports additional javac options. They can be given either as package settings or as a separate file placed in the project folder:
- https://github.com/AtomLinter/linter-javac/wiki/additionalJavacOptions
- https://github.com/AtomLinter/linter-javac/wiki/javacArgsFilename

**Comment by torkelrogstad** [comment]
Oh geez, this is kinda embarrassing... Thanks a lot for pointing that out! Didn't even know there was a wiki with this kind of information...
