### ISSUE TITLE
Help need, Linter-javac output question mark ??: ??ASCII???????

### ISSUE THREAD

**Issue by baozilala** [AtomLinter/linter-javac#111]
> /Users/xxx/Documents/Java Project/1st/HelloWorld.java:3: ??: ??ASCII???????
>     System.out.println("HelloWorld!??????");

My os is OS X EI Capitan with latest Atom.

When I used cmd+i, Linter-javac will output ??? marks and my system language is Chinese, will it affect?

**# sorry guys i think this issue come from Script, not because of linter-javac**

**Comment by baozilala** [comment]
Yep!
After change my system language to English, the errors changed:

> /Users/xxx/Documents/Java Project/1st/HelloWorld.java:3: error: unmappable character for encoding ASCII
>     System.out.println("HelloWorld!??????");

**Comment by florianb** [comment]
Hi @baozilala - thanks for getting in touch! I am happy this is no bug on our side.

However, you might want to take a look at #36 which was our origin issue starting to support linting javac on Chinese environments. Feel free to come back if you have questions & good luck!
