### ISSUE TITLE
Unused import statements are not checked

### ISSUE THREAD

**Issue by alexandros369** [AtomLinter/linter-javac#119]
Hello :relaxed: 
It is great for having this atom package! Since I got a slow laptop and it drives me crazy when it runs eclipse or intellij idea really slow, i prefer to use a light-weight text editor such as atom when i'm not at work to do my coding. 

So this is not an issue i am having but an idea for improvement of the linter. My idea is that it would be nice if the linter checked for unused import statements as well :slightly_smiling_face: 

Thanks for finding time for checking this post. Keep up the good work! :+1: :heart:

**Comment by Arcanemagus** [comment]
This "linter" is just a wrapper around `javac`, as such it only reports compiler errors. You can try checking out [ide-java](https://atom.io/packages/ide-java), but as it uses the same LSP that Eclipse does it will likely be more load on your system than you want.

**Comment by florianb** [comment]
Hi @alexandros369 - thanks for getting in touch. @Arcanemagus is right, this package just displays warnings/error generated by the java-compiler.

I'd like to refer to static code analyzers for this task: https://stackoverflow.com/questions/97599/static-analysis-tool-recommendation-for-java
