### ISSUE TITLE
my linter-javac doesnt know "this." ?

### ISSUE THREAD

**Issue by felixjustus** [AtomLinter/linter-javac#120]
Hey there,I love the linter package! It became one of my fav packages :). We're learning Objects in Java (first semester in my uni) and the linter underlines mostly the "t" from "this.a" for example, sometimes just the dott./whitespace It's not a biggie but I just wanted to tell you guys and hope youre gonna fix it 🌵.
For example:
`  public Polynom(int a, int b, int c, int d,){
    this.a = a;
    this.b = b;
    this.c = c;
    this.d = d;
  }`
Greetz, Felix.

**Comment by Arcanemagus** [comment]
This is essentially only a wrapper around running `javac -Zlint:all file.java`, so either this is a bug in `javac`, or something wrong with your code 😉.

----

It's been many years since I last messed with Java code, but I would guess that maybe you forgot the wrapping `public class Polynom`?

```java
public class Polynom {
  public Polynom(int a, int b, int c, int d,){ this.a = a; this.b = b; this.c = c; this.d = d; }
}
```

**Comment by Arcanemagus** [comment]
You also may be interested in checking out the [ide-java](https://atom.io/packages/ide-java), it provides linting (I'm not sure how it compares to `javac`), as well as many other features such as autocompletion. You'll want to install [atom-ide-ui](https://atom.io/packages/atom-ide-ui) for all the additional functionality.

You can keep using `linter` for the messages if you prefer its interface, or you can use `atom-ide-ui` for that as well.

Note that if `ide-java` isn't finding all of the lints you are used to, you can keep using this package at the same time 😉.
