### ISSUE TITLE
Older atom version

### ISSUE THREAD

**Issue by michaelkrasa** [AtomLinter/linter-javac#129]
Atom at our school's computers isn't the latest version but until yesterday everything worked great. The new version unfortunately isn't compatible with my version of atom. I tried installing an older release of linter-javac but nothing in atom suggests that its working. 

Atom's version is 1.14.3 and I tried installing versions 1.9.4 and 1.9.2 of linter-javac.

Any ideas how to get it working without updating atom?

Thank you

**Comment by Arcanemagus** [comment]
If the older versions (that were presumably working) aren't working any more then that would suggest the problem isn't with the version of `linter-javac`. All you have said is "nothing suggests that its working", which doesn't give much to go on.

Atom v1.14.3 is _ancient_, if you can't get your school to update the version they have installed on their image I would recommend running a [Portable Version](https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode) of Atom to stay up to date.
