### ISSUE TITLE
2 deprecations warnings with current API

### ISSUE THREAD

**Issue by jplatte** [AtomLinter/linter-javac#14]
Since some versions (currently I'm on 0.196.0) I'm getting 2 warnings about linter-javac from Deprecation Cop:

(1)

    Use a config schema instead. See the configuration section of https://atom.io/docs/latest/hacking-atom-package-word-count and https://atom.io/docs/api/latest/Config for more details

    Package.activateConfig - /usr/share/atom/resources/app.asar/src/package.js:247:11
    Package.activateNow - /usr/share/atom/resources/app.asar/src/package.js:218:14
    <unknown> - /usr/share/atom/resources/app.asar/src/package.js:203:30
    Package.measure - /usr/share/atom/resources/app.asar/src/package.js:147:15

(2)

    Use activationCommands instead of activationEvents in your package.json Commands should be grouped by selector as follows:

      "activationCommands": {
        "atom-workspace": ["foo:bar", "foo:baz"],
        "atom-text-editor": ["foo:quux"]
      }

    Package.getActivationCommands - /usr/share/atom/resources/app.asar/src/package.js:790:9
    Package.hasActivationCommands - /usr/share/atom/resources/app.asar/src/package.js:715:20
    <unknown> - /usr/share/atom/resources/app.asar/src/package.js:169:24
    Package.measure - /usr/share/atom/resources/app.asar/src/package.js:147:15

**Comment by skylineproject** [comment]
Hi jplatte! 

It looks like these deprecations are in ```atom core```, not the ```linter-javac``` package. 
![screen shot 2015-05-04 at 8 30 27 am](https://cloud.githubusercontent.com/assets/5009403/7454295/da733846-f237-11e4-8ff9-52c75c778a93.png)

You can tell which package is causing the deprecation warnings based on the dropdown menu that contains them.

**Comment by jplatte** [comment]
![screenshot from 2015-05-04 16-33-40](https://cloud.githubusercontent.com/assets/951129/7455320/67aab3b8-f27b-11e4-8c18-0b3cfb867f7a.png)

**Comment by skylineproject** [comment]
Nice! I stand corrected. See the attached PR (you can apply it to your own install if you like!) for a resolution.

**Comment by jplatte** [comment]
Thanks! (though I'll wait for the next release, the small warning icon isn't much of a problem :smile:)

**Comment by skylineproject** [comment]
Totally. :) 

To be honest, I'm not 100% certain this repo is still being maintained(?) There are gobs of stale PR's and issues hanging out here... 

@florianb, are you still the core committer?

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/AtomLinter/linter-javac/pull/15
