### ISSUE TITLE
Config.unobserve is deprecated.

### ISSUE THREAD

**Issue by florinbroasca** [AtomLinter/linter-javac#17]
Config::unobserve no longer does anything. Call `.dispose()` on the object returned by Config::observe instead.
```
Config.unobserve (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:1060:19)
LinterJavac.destroy (/Users/florin/.atom/packages/linter-javac/lib/linter-javac.coffee:27:16)
LinterView.remove (/Users/florin/.atom/packages/linter/lib/linter-view.coffee:252:6)
<unknown> (/Users/florin/.atom/packages/linter/lib/linter-view.coffee:124:7)
```

**Comment by skylineproject** [comment]
Please see pull requests #13 and #15 for fixes to this issue. I'm not a maintainer of this package, so I can't commit this to a release, but I'm trying to help bring this package up to date where I can. I'd love to have your feedback!
