### ISSUE TITLE
Package.getActivationCommands is deprecated.

### ISSUE THREAD

**Issue by florinbroasca** [AtomLinter/linter-javac#19]
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:810:9)
Package.hasActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:735:20)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:189:24)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
```

**Comment by skylineproject** [comment]
Hey Florin! As previously, I have repaired this in my own fork of the repo. We can't seem to get ahold of the repository maintainers, so I've made the change in my own repo and submitted PRs. If you'd like to remove these errors in the meantime, you can also use my fork of this repo, which doesn't exhibit these issues.

To install, run:

```git clone https://github.com/skylineproject/linter-javac.git ~/.atom/packages/linter-javac```

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/AtomLinter/linter-javac/pull/15
