### ISSUE TITLE
Enable the javac-configuration from package settings

### ISSUE THREAD

**Issue by florianb** [AtomLinter/linter-javac#2]
Most important options/settings:

- `-source release` (1.3-1.8) - free text field?

**Comment by keskiju** [comment]
A free text field that contains additional parameters passed to javac during linting. Although some settings are usually project specific so a project specific settings file would be nice.

**Comment by daw42** [comment]
@keskiju I agree that per-project configuration would be useful.  I recently submitted a pull request ( #30 ) that would allow for per-project configuration via CSON files (initially for classpath, but could be expanded to include other options such as arbitrary `javac` parameters).  However, the project maintainer felt that it was important to support a pre-existing standard set by `linter-scalac`, and use `.classpath` files instead (see discussion on #30).  @k2b6s9j, perhaps you would like to give your thoughts on this?

**Comment by keskiju** [comment]
Uniformity between plugins is always a good thing. Currently someone is developing java-importer plugin for Atom and it would be handy if eventually both linter-javac and java-importer plugins would use the same classpath settings from the .classpath file.

However, there might be a small problem with the .classpath file approach. It might cause conflicts between different editor conventions if some of the developers use some other editor than Atom. For example Eclipse uses .classpath file that is in eclipse specific xml format. Perhaps Atom plugins should first search for atom a specific configuration file (f.ex. .classpath.atom) and only then search for a .classpath file that might be used by other editors also.

**Comment by florianb** [comment]
@daw42: thanks for your support :smile: -- unfortunately the `.classpath`-file has its origin in the Eclipse-domain, which is why this file (imho) shouldn't be used to extend further functionalities like storing other parameters than class-references.

I see a strong need for a standardized project-based configuration -- i'll try to bring that into discussion for the whole atom-linter-plugin.

**Comment by florianb** [comment]
In order to solve the `.classpath`-issue #62 i carried this discussion to https://github.com/atom-community/linter/issues/744. The overall consensus is to swap that kind of functionality to the project-manager plugin.

So i'd like to close that issue for now - feel free to pick the discussion up.. :lollipop:
