### ISSUE TITLE
Maven Java Project

### ISSUE THREAD

**Issue by eltados** [AtomLinter/linter-javac#21]
Is there a way to configure linter-javac to work with maven ?

**Comment by adben** [comment]
+1 to this

**Comment by eltados** [comment]
that is not really a long term solution IMO ...

**Comment by k2b6s9j** [comment]
I am planning on creating more project based linters like linter-gradle, and linter-maven.

**Comment by k2b6s9j** [comment]
And linter-ant.

**Comment by eltados** [comment]
Cool @k2b6s9j  give me a shout if you want help to test  ( or to implement but that would be a first module for me ) the linter-maven.

**Comment by k2b6s9j** [comment]
Of course.

**Comment by kepler0** [comment]
I no longer plan to create linters for these scenarios, rather the should be done in a package designed for building. Please see, [`atom-build`](https://atom.io/packages/build). It is organized like `linter` is and integration between `linter` and `build` is in the works.
