### ISSUE TITLE
Regex is getting incorrect results in some cases

### ISSUE THREAD

**Issue by daw42** [AtomLinter/linter-javac#28]
The `errRegex` captures too much of the string in some cases.  

For example, this one works fine

`Test.java:12: error: method doFoo in class Test cannot be applied to given types`

the word "error" is captured properly.

But this one doesn't work:

`Test.java:8: error: incompatible types: possible lossy conversion from float to int`

it captures `error: incompatible types`, instead of just `error`.

This ends up in causing a error from the linter:  `InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('error:-incompatible types') contains HTML space characters, which are not valid in tokens.`

The regex needs to be fixed to be more restrictive.  I suggest we go back to:  `(error|warning)` for now.

**Comment by k2b6s9j** [comment]
I can fix this by replacing the regex with: `/^(.*\.java):(\d+): ([\w \-]+): (.+)/`.

I will do this now.

**Comment by k2b6s9j** [comment]
Proof: https://regex101.com/r/vK9dM3/1.

**Comment by k2b6s9j** [comment]
@daw42 If you could give me a file which produces this issue, I'd love to incorporate this into a unit test one day.

**Comment by daw42** [comment]
Here's a file that produces the incompatible types error:

``` java
public class Test {
  public static void main( String[] args )
  {
     int a; float b;
     a = b;
  }
}

```
