### ISSUE TITLE
not auto creating class file anymore

### ISSUE THREAD

**Issue by Jarvvski** [AtomLinter/linter-javac#37]
This used to auto create the class file for me when saving in atom for mac.

That functionality seems to have been lost?

**Comment by ilikebits** [comment]
This functionality seems to be unintended (see #35).

**Comment by Jarvvski** [comment]
I see.

Would it be possible to allow the two options in the settings? I for one enjoy not having to javac every time I need to build, just so I can Java the output

**Comment by kepler0** [comment]
I would like to make this a Boolean Configuration Option, defaulted to not generating source files.

**Comment by kepler0** [comment]
Closing and moving into #35.
