### ISSUE TITLE
spawn E2BIG when linting

### ISSUE THREAD

**Issue by drakecaiman** [AtomLinter/linter-javac#38]
I am getting spawn E2BIG errors when saving .java files in Atom.

It might have something to do with the number of files in the project folder, as open a window including only a single folder from the project does not produce the error.

#### Steps
* Make changes to an open .java file
* Save file

#### Expected:
Atom updates linter display without error
#### Actual:
No linting, following error displayed:

<img width="453" alt="screen shot 2015-11-19 at 1 55 28 pm" src="https://cloud.githubusercontent.com/assets/870130/11282529/6164fe5a-8ec5-11e5-9306-616b7a5f0ec0.png">

#### Setup:
Atom 1.2.3
Mac OS X 10.11.1

**Comment by steelbrain** [comment]
If I had to guess, you have specified an invalid executable path in the configuration

**Comment by drakecaiman** [comment]
The package settings (javaExecutablePath)? Without changing the path setting (on default), it seems to work fine with a smaller Tree View (seven folders deep, 200 files), but not when the tree view's root is one directory up (~5,000 files).

**Comment by noseglid** [comment]
I've seen the same issue. `E2BIG` is a unix error where the executed command is too long. That includes the classpath set from the `.classpath` file, all the java files found by traversing the tree and adding them.

I managed to get it to work by reducing my classpath to an acceptable length, but that's just gonna work for so long. A change in the linter plugin is needed where stuff to `javac` is passed in a different way.

**Comment by florianb** [comment]
This problem may likely be avoided, by moving the classpath-argument to the [option-parameter](https://github.com/AtomLinter/atom-linter/blob/master/lib/helpers.js#L65) (`options.env.CLASSPATH`) of the executing command.

**Comment by florianb** [comment]
In favor of #58 i'm closing this issue for now. :godmode:
