### ISSUE TITLE
Can not make javac linter work

### ISSUE THREAD

**Issue by anxolerd** [AtomLinter/linter-javac#4]
Installed this package (Linter is installed too), but nothing happens when i open .java files that contain syntax errors. Tried to set javaExecutablePath to C:\\Program Files\\Java\\jdk1.8.0.5\\bin\\javac.exe.  C:\\Program Files\\Java\\jdk1.8.0.5\\bin\\, C:\\Program Files\\Java\\jdk1.8.0.5\\bin (javac is 100% there) Results were the same.

OS: Windows 7 Home Basic x64
Java is for x64
Atom is built for x32 System

**Comment by daw42** [comment]
Looks like this has been resolved.  Perhaps it should be closed?
