### ISSUE TITLE
.classpath syntax

### ISSUE THREAD

**Issue by sn1p3r46** [AtomLinter/linter-javac#41]
Hello, thanks for the great plugin you developed. 

I am having troubles with the .classpath file, could you provide some examples for a complex .classpath file? 

The plugin does not work when I add multiple path, but I guess is a problem of mine not of the plugin.

Thanks a lot 
Andrea

**Comment by RomuloPBenedetti** [comment]
I would like it too, in my case I have a project with "sub-projects"
with gradle builds, one of them is java, I've put paths from my repository root where is ```.classpath```:

    ./subproject(java)/src/main/java:
    ./subproject(java)/build/classes/main:
    ./subproject(java)/lib/*

As you can see I don't include in my paths, package folders.
And I would like to know why ```.class``` files are being generated within my ```.java``` files.

**Comment by Arcanemagus** [comment]
The `.classpath` file is part of `javac`, not this package. This is just a simple intermediary that runs that, parses its output, and sends it to linter.

I was trying to find some examples to put in the readme anyway... but I wasn't having much luck from a quick Google search. @kepler0 since you've done most of the recent work on this do you have any good examples or resources about them? Last time I touched Java code was over 10 years ago...

**Comment by RomuloPBenedetti** [comment]
There is no reference to this method of declaring class files location in [javac documentation](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html).
Some other packages as autocomplete-java are using this concept, But it takes the same example as point.

**Comment by Arcanemagus** [comment]
The answers to this are really all that I've been able to find: http://stackoverflow.com/questions/7186676/whats-in-an-eclipse-classpath-project-file

**Comment by florianb** [comment]
The `.classpath`-file is originated at the eclipse-project (unfortunatels i couldn't find any good resource documenting its xml-structure, but at least a [semi-good](http://www.javabeat.net/editing-eclipse-classpath-file/) one). Other tools like Maven, Gradle and Netbeans are able to read or generate thos `.classpath` files, so i guess for a normal developer workflow this might be the most unobtrusive way to enable classpath-recognition.

**Comment by florianb** [comment]
Since it looks like that a few issues touch the use of `.classpath`-files i swapped that topic into a different issue.

For the reasons in the issue #62 - i would like to allow the classpath-settings over the configuration only. I appreciate any thoughts.

**Comment by florianb** [comment]
The classpath concerns will be bundled in the new and shiny [`atom-javaenv`-package](javaenv) - it will be introduced with the next major-release #76.

Thank you all for your contribution and thoughts on this topic! :gift_heart: 

[javaenv]: https://github.com/florianb/atom-javaenv
