### ISSUE TITLE
Synchronously walking file system

### ISSUE THREAD

**Issue by noseglid** [AtomLinter/linter-javac#44]
Atom locks up while walking the file system searching for all files. This gives a bad use experience and makes everything feel sluggish.

Using promises and the async versions of the `fs` functions should make this smoother.

**Comment by steelbrain** [comment]
@kepler0 this seems reasonable, should we add an async findFile helper in the helper module?

**Comment by kepler0** [comment]
@steelbrain That seems like a useful addition. Talk with @noseglid on Slack about adding it to the module.
