### ISSUE TITLE
Implement specs

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-javac#55]
It looks like this linter does not currently have any specs written for it, adding it to the list being maintained [here](https://github.com/AtomLinter/Meta/issues/11) for tracking.

Specs do not need to be super detailed, as they should mainly test whether the package is properly running the linter plugin and parsing its messages. Leave testing of the linter functionality to the author of the linter.

If you need any help feel free to ask!

**Comment by florianb** [comment]
Fundamental specs implemented.

The whole test-arrangement could be improved f.e. by mocking more the `javac`-dependency (see #70).

**Comment by Arcanemagus** [comment]
Thanks!

**Comment by florianb** [comment]
@Arcanemagus you're welcome - :+1: I'm merging it in with the upcoming release..

**Comment by florianb** [comment]
@steelbrain - i am still working on the tests and i have a question (which i already posted on Slack), is there a way to obtain the linted messages from within a running atom-environment?

**Comment by steelbrain** [comment]
Usually the way we test linter providers is,
```js
linter = getProvider()
const results = await linter.lint(textEditor)
expect(results.length).toBe(1)
expect(results[0]).toEqual({type: 'Error', text: 'something', filePath: '/path/to/file'})
```

**Comment by florianb** [comment]
Hmm, `getProvider()` is currently unavailable since i tried to not instantiate the linter on my own but use the instance created by atom. But i guess that's just not possible.

**Comment by florianb** [comment]
Thanks anyways! I'm going to instantiate the linter again.. :candy:
