### ISSUE TITLE
Enable optional linting on the fly again

### ISSUE THREAD

**Issue by florianb** [AtomLinter/linter-javac#66]
Enable optional linting on the fly by implementing a one-slot queue for pending lint-requests and a parallelized linter-execution based on `atom.Task`.

The mode should be switchable in the configuration settings.

**Comment by Arcanemagus** [comment]
For an alternative implementation you can check out `linter-eslint` as it also spawns a separate process to do the work so Atom isn't blocked waiting on results.

**Comment by florianb** [comment]
Thanks @Arcanemagus -  `linter-eslint` inspired me to consider this enhancement. I already implemented a similar mechanism in the gradle-ci plugin.

**Comment by florianb** [comment]
I put this issue on the next major-release: #76
