### ISSUE TITLE
Does not lint. atom.project.getPaths(...).sort(...).find is not a function

### ISSUE THREAD

**Issue by bkazi** [AtomLinter/linter-javac#68]
The error below is produced on a save running Atom on Ubuntu Gnome Wily with only one project folder in use

```
TypeError: atom.project.getPaths(...).sort(...).find is not a function
    at Object.module.exports.getProjectRootDir (/home/bkazi/.atom/packages/linter-javac/lib/init.coffee:109:8)
    at Object.lint (/home/bkazi/.atom/packages/linter-javac/lib/init.coffee:39:20)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/bkazi/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/bkazi/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/bkazi/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/bkazi/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /home/bkazi/.atom/packages/linter/lib/editor-linter.js:30:20
```

find isn't recognized as an Atom function
Any ideas for a fix?

**Comment by Arcanemagus** [comment]
@florianb I'm guessing this is a case where there is no open project, just a raw file. @clamey just put up a brilliantly simple method of getting the project path in https://github.com/AtomLinter/linter-csslint/pull/79, you might want to move to that from this current code (handling files not in a project of course).

**Comment by florianb** [comment]
@bkazi thanks for reporting this issue! :cake:

@Arcanemagus thanks for the hint, i'm going to investigate that. Fortunately i have already some experiences with facy project-path-relations.

I will start investigating after the test-implementation which hopefully will happen today.. :date:

**Comment by bkazi** [comment]
Update:
There seems to be no issue and linting does take place after updating Atom to 1.5.1, since I realised that I was still using 1.0.19 and not been receiving updates over the air 

Hope that helps

**Comment by florianb** [comment]
Aye - thanks @bkazi :lollipop:

 I'll take that in consideration, probably @NanoDami uses an older version of Atom, too?

**Comment by Arcanemagus** [comment]
Ah, if you were on that old of a version of Atom it's possible core JS features this relies on were missing before.

**Comment by NanoDami** [comment]
I don't have that particular laptop with me now, but i can check once i get back home. It sounds like that might be the case and now i feel like an idiot =P

**Comment by Arcanemagus** [comment]
@NanoDami it's not your fault Atom needs work on it's autoupdate feature :wink:.

**Comment by florianb** [comment]
@NanoDami please do not! Even if this an issue is caused by Atom it could lead to a filed :bug: in the core-repo. And probably there is still a chance to avoid this in general, because our Atom-dependency is set wrong, or we need to refactor the API-use.

So thanks again.. :+1: 

P.s.: we should consider raising the Atom-dependency to a "tested" level..

**Comment by Arcanemagus** [comment]
@florianb No real harm, worst case some users realize they need to update their Atom installations :wink:.

**Comment by florianb** [comment]
I put this issue on hold until @NanoDami has ensured that the bug also appears with an up to date atom. :watch:

**Comment by florianb** [comment]
This issue is currently not testable and therefore put to the next major release: #76

**Comment by florianb** [comment]
Due to the fact that updating Atom fixed that for @bkazi and @NanoDami didn't respond yet i'll close that issue for now. Feel free to add anything to the thread.

Thanks everybody! :candy:
