### ISSUE TITLE
helper.exec() should be stubbed

### ISSUE THREAD

**Issue by florianb** [AtomLinter/linter-javac#70]
The helper.exec()-function should be stubbed or mocked to remove the test-dependency on a installed java-env.

Edit:
Stderr-outputs for Mac javac_1.8.0_74 are already provided in the fixture-directory.

**Comment by Arcanemagus** [comment]
Actually I'd say this is a rather bad idea. If the `javac` output itself changes on you, your tests will fail to show that anything is wrong (For example in linter-php I saw that PHP7 had fixed a bug in the output that I was unintentionally relying on to parse the output).

**Comment by florianb** [comment]
Absolutely true - i stumbled over that, too. On the other hand i'd like to be able to test against formal stderr-outputs.

To get around that problem i would add a stderr-log per every issued compiler-version. I mean we rely on the formal javac output since this plugin exists and nothing changed there, yet. I consider the risk as being low.

Additionally i could add a test which does run the compiler checks for version and bug-formatting.

**Comment by florianb** [comment]
# Improve Specs

- [ ] Add mocked helper.exec per possible java version (at least 6, 7, 8)
- [ ] Add local base-spec to test the functionality of the package on the platform in use

**Comment by florianb** [comment]
This issue is part of the refactoring: #76
