### ISSUE TITLE
linter-javac complains about regular UTF8 characters

### ISSUE THREAD

**Issue by nicolaiskogheim** [AtomLinter/linter-javac#9]
linter-javac 0.1.3
atom 0.131.0

This was not a problem before.
The reported file format from `file`-utility in terminal gives `Main.java: UTF-8 Unicode c program text`

I actually don't know who's to blame for this, because it happened when I updated from atom 0.129.0 to 0.131.0. Java-files I created prior to that have this encoding (again reported by `file`) `Main.java: UTF-8 Unicode Java program text`, BUT this apparently is not the issue because I get the same errors with those old "java-encoded" files.

![Screenshot from Atom](https://www.dropbox.com/s/xcuii02mbba7wan/Screenshot%202014-09-26%2012.31.50.png?dl=1)

The characters are maybe hard to see on the image, but it's things like `æøåéèô`.

For the record: Compiling and running the files works as expected.

**Comment by skylineproject** [comment]
Hey Nicolai,

I've dug a little further into some of the issues I was experiencing with this package, and some of the other issues I've seen on this repo, and I think this may have been repaired in more recent versions of Atom. 

In Atom 0.190.0, these exact same unicode characters seem to return no errors: 
![linter-javac likes unicode now, yay](https://cloud.githubusercontent.com/assets/5009403/7104080/1b84ddec-e08d-11e4-9248-c669268d3a9b.png)

Have you tested more recent versions of Atom? I know that there hasn't been any activity on this issue from the maintainers as I write this, but if you're still interested to get this fixed, I bet we could figure it out together!

Best,

Brandon (skylineproject)

**Comment by nicolaiskogheim** [comment]
Sorry, I switched editor about the time this happened and forgot all about it.
The errors I referred to are all gone now.

Thank you for the follow up.

Med vennlig hilsen, 

Nicolai
