### ISSUE TITLE
linter-javac only works while saving the file.

### ISSUE THREAD

**Issue by janoop** [AtomLinter/linter-javac#93]
Python-linter allows a feature to check the code when there is any changes made but linter-javac only checks for error when file is saved or compiled.

So i want to know that is there any way that linter-javac performs a check when there is any changes made in file.

**Comment by Arcanemagus** [comment]
The primary thing preventing such a possibility is that this is actually compiling your code and parsing any errors output... thus it needs _all_ files in the project. Secondly it's unlikely that `javac` supports running on a file sent in via `stdin`.

If both of those can be worked around feel free to open this up again.
